version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  redis:
    image: redis

  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn django_app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  nginx:
      build:
        context: .
        dockerfile: nginx/Dockerfile
      depends_on:
        - web
      ports:
        - "80:80"
      container_name: django_nginx

  celery:
    build: .
    command: celery -A django_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A django_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
       - db
       - redis