version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  redis:
    image: redis

  web:
    build: .
    command: gunicorn django_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  nginx:
      build:
        context: .
        dockerfile: nginx/Dockerfile
      depends_on:
        - web
      ports:
        - "80:80"
      container_name: django_nginx